import React from "react";
import { View } from "react-native";
import { useRecoilState } from "recoil";
import { storeId as _storeId } from '../atoms'
import { gql } from "../__generated__";
import * as Linking from 'expo-linking';
import { useMutation } from "@apollo/client";
import Button from '../components/Button'

const OAUTH_URL = `https://connect.squareup.com/oauth2/authorize?client_id=🤫&scope=BANK_ACCOUNTS_READ+BANK_ACCOUNTS_READ+BANK_ACCOUNTS_READ+APPOINTMENTS_WRITE+APPOINTMENTS_WRITE+APPOINTMENTS_ALL_WRITE+APPOINTMENTS_READ+APPOINTMENTS_READ+APPOINTMENTS_ALL_READ+APPOINTMENTS_BUSINESS_SETTINGS_READ+APPOINTMENTS_BUSINESS_SETTINGS_READ+APPOINTMENTS_BUSINESS_SETTINGS_READ+APPOINTMENTS_READ+APPOINTMENTS_READ+APPOINTMENTS_ALL_READ+APPOINTMENTS_READ+APPOINTMENTS_READ+APPOINTMENTS_ALL_READ+APPOINTMENTS_WRITE+APPOINTMENTS_WRITE+APPOINTMENTS_ALL_WRITE+APPOINTMENTS_WRITE+APPOINTMENTS_WRITE+APPOINTMENTS_ALL_WRITE+APPOINTMENTS_WRITE+APPOINTMENTS_WRITE+APPOINTMENTS_ALL_WRITE+APPOINTMENTS_WRITE+APPOINTMENTS_WRITE+APPOINTMENTS_ALL_WRITE+APPOINTMENTS_READ+APPOINTMENTS_READ+APPOINTMENTS_ALL_READ+APPOINTMENTS_READ+APPOINTMENTS_READ+APPOINTMENTS_ALL_READ+APPOINTMENTS_WRITE+APPOINTMENTS_WRITE+APPOINTMENTS_ALL_WRITE+APPOINTMENTS_WRITE+APPOINTMENTS_WRITE+APPOINTMENTS_ALL_WRITE+APPOINTMENTS_WRITE+APPOINTMENTS_WRITE+APPOINTMENTS_ALL_WRITE+APPOINTMENTS_READ+APPOINTMENTS_READ+APPOINTMENTS_ALL_READ+APPOINTMENTS_READ+APPOINTMENTS_READ+APPOINTMENTS_ALL_READ+APPOINTMENTS_WRITE+APPOINTMENTS_WRITE+APPOINTMENTS_ALL_WRITE+PAYMENTS_READ+PAYMENTS_WRITE+PAYMENTS_READ+PAYMENTS_WRITE+CASH_DRAWER_READ+CASH_DRAWER_READ+CASH_DRAWER_READ+ITEMS_WRITE+ITEMS_WRITE+ITEMS_READ+ITEMS_READ+ITEMS_WRITE+ITEMS_WRITE+ITEMS_READ+ITEMS_READ+ITEMS_READ+ITEMS_READ+ITEMS_WRITE+ITEMS_WRITE+ITEMS_WRITE+ORDERS_WRITE+ORDERS_READ+PAYMENTS_WRITE+CUSTOMERS_WRITE+CUSTOMERS_WRITE+CUSTOMERS_WRITE+CUSTOMERS_WRITE+CUSTOMERS_WRITE+CUSTOMERS_READ+CUSTOMERS_WRITE+CUSTOMERS_READ+CUSTOMERS_READ+CUSTOMERS_WRITE+CUSTOMERS_WRITE+CUSTOMERS_WRITE+CUSTOMERS_READ+CUSTOMERS_READ+CUSTOMERS_WRITE+CUSTOMERS_WRITE+CUSTOMERS_WRITE+CUSTOMERS_READ+CUSTOMERS_READ+CUSTOMERS_WRITE+CUSTOMERS_WRITE+CUSTOMERS_WRITE+CUSTOMERS_READ+CUSTOMERS_READ+CUSTOMERS_WRITE+CUSTOMERS_READ+CUSTOMERS_READ+DEVICE_CREDENTIAL_MANAGEMENT+DEVICE_CREDENTIAL_MANAGEMENT+DEVICE_CREDENTIAL_MANAGEMENT+DISPUTES_WRITE+DISPUTES_WRITE+DISPUTES_WRITE+DISPUTES_READ+DISPUTES_READ+DISPUTES_WRITE+DISPUTES_READ+DISPUTES_READ+DISPUTES_WRITE+EMPLOYEES_READ+EMPLOYEES_READ+GIFTCARDS_READ+GIFTCARDS_WRITE+GIFTCARDS_READ+GIFTCARDS_READ+GIFTCARDS_WRITE+GIFTCARDS_WRITE+GIFTCARDS_READ+GIFTCARDS_READ+GIFTCARDS_WRITE+INVENTORY_WRITE+INVENTORY_READ+INVENTORY_READ+INVENTORY_READ+INVENTORY_READ+INVENTORY_READ+INVENTORY_READ+INVOICES_READ+ORDERS_WRITE+INVOICES_WRITE+INVOICES_READ+ORDERS_WRITE+INVOICES_WRITE+INVOICES_READ+ORDERS_WRITE+INVOICES_WRITE+ORDERS_WRITE+INVOICES_WRITE+ORDERS_WRITE+INVOICES_WRITE+TIMECARDS_SETTINGS_WRITE+TIMECARDS_WRITE+TIMECARDS_SETTINGS_WRITE+TIMECARDS_WRITE+TIMECARDS_SETTINGS_READ+EMPLOYEES_READ+TIMECARDS_READ+TIMECARDS_SETTINGS_READ+EMPLOYEES_READ+TIMECARDS_SETTINGS_READ+TIMECARDS_READ+TIMECARDS_WRITE+TIMECARDS_READ+TIMECARDS_SETTINGS_READ+TIMECARDS_SETTINGS_WRITE+TIMECARDS_SETTINGS_READ+TIMECARDS_SETTINGS_WRITE+MERCHANT_PROFILE_WRITE+MERCHANT_PROFILE_READ+MERCHANT_PROFILE_READ+MERCHANT_PROFILE_WRITE+MERCHANT_PROFILE_WRITE+MERCHANT_PROFILE_WRITE+MERCHANT_PROFILE_READ+MERCHANT_PROFILE_READ+MERCHANT_PROFILE_WRITE+MERCHANT_PROFILE_WRITE+MERCHANT_PROFILE_WRITE+MERCHANT_PROFILE_READ+MERCHANT_PROFILE_READ+MERCHANT_PROFILE_WRITE+MERCHANT_PROFILE_WRITE+LOYALTY_READ+LOYALTY_READ+LOYALTY_WRITE+LOYALTY_READ+LOYALTY_READ+LOYALTY_WRITE+LOYALTY_WRITE+LOYALTY_READ+LOYALTY_READ+LOYALTY_WRITE+LOYALTY_WRITE+LOYALTY_READ+LOYALTY_WRITE+LOYALTY_WRITE+LOYALTY_READ+LOYALTY_READ+LOYALTY_WRITE+LOYALTY_READ+MERCHANT_PROFILE_READ+MERCHANT_PROFILE_READ+MERCHANT_PROFILE_WRITE+MERCHANT_PROFILE_WRITE+MERCHANT_PROFILE_READ+MERCHANT_PROFILE_READ+MERCHANT_PROFILE_WRITE+MERCHANT_PROFILE_WRITE+MERCHANT_PROFILE_WRITE+MERCHANT_PROFILE_READ+MERCHANT_PROFILE_READ+MERCHANT_PROFILE_WRITE+MERCHANT_PROFILE_WRITE+PAYMENTS_WRITE_IN_PERSON+ORDERS_WRITE+ORDERS_WRITE+ORDERS_READ+ORDERS_WRITE+PAYMENTS_WRITE+ORDERS_WRITE+ORDERS_READ+ORDERS_READ+ORDERS_WRITE+ORDERS_WRITE+ORDERS_WRITE+ORDERS_READ+ORDERS_READ+ORDERS_WRITE+ORDERS_WRITE+ORDERS_WRITE+ORDERS_READ+ORDERS_READ+ORDERS_WRITE+ORDERS_WRITE+PAYMENTS_WRITE+PAYMENTS_WRITE+PAYMENTS_WRITE+PAYMENTS_WRITE+PAYMENTS_WRITE_SHARED_ONFILE+PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS+PAYMENTS_READ+PAYMENTS_READ+PAYMENTS_READ+PAYMENTS_READ+PAYMENTS_WRITE+PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS+PAYOUTS_READ+PAYOUTS_READ+PAYOUTS_READ+ONLINE_STORE_SITE_READ+ONLINE_STORE_SNIPPETS_WRITE+ONLINE_STORE_SNIPPETS_READ+ONLINE_STORE_SNIPPETS_WRITE+CUSTOMERS_READ+PAYMENTS_WRITE+SUBSCRIPTIONS_WRITE+ITEMS_READ+ORDERS_WRITE+INVOICES_WRITE+SUBSCRIPTIONS_READ+SUBSCRIPTIONS_READ+CUSTOMERS_READ+PAYMENTS_WRITE+SUBSCRIPTIONS_WRITE+ITEMS_READ+ORDERS_WRITE+INVOICES_WRITE+SUBSCRIPTIONS_WRITE+SUBSCRIPTIONS_READ+CUSTOMERS_READ+PAYMENTS_WRITE+SUBSCRIPTIONS_WRITE+ITEMS_READ+ORDERS_WRITE+INVOICES_WRITE+CUSTOMERS_READ+PAYMENTS_WRITE+SUBSCRIPTIONS_WRITE+ITEMS_READ+ORDERS_WRITE+INVOICES_WRITE+CUSTOMERS_READ+PAYMENTS_WRITE+SUBSCRIPTIONS_WRITE+ITEMS_READ+ORDERS_WRITE+INVOICES_WRITE+SUBSCRIPTIONS_WRITE+EMPLOYEES_WRITE+EMPLOYEES_WRITE+EMPLOYEES_WRITE+EMPLOYEES_WRITE+EMPLOYEES_READ+EMPLOYEES_READ+EMPLOYEES_READ+EMPLOYEES_WRITE+PAYMENTS_WRITE+PAYMENTS_WRITE+PAYMENTS_READ+PAYMENTS_READ+PAYMENTS_WRITE+PAYMENTS_WRITE+PAYMENTS_READ+PAYMENTS_READ+PAYMENTS_WRITE+PAYMENTS_WRITE+PAYMENTS_READ+CUSTOMERS_READ+PAYMENTS_READ+VENDOR_WRITE+VENDOR_READ+VENDOR_WRITE+VENDOR_WRITE+VENDOR_READ+VENDOR_READ+VENDOR_WRITE&session=false&state=`

function signIn(url: string) {
    Linking.openURL(OAUTH_URL + encodeURIComponent(url))
}

const SYNC_COUPONS = gql(`
    mutation SyncCoupons($store_id: String!) {
        syncCoupons(store_id: $store_id)
      }
`)

export default () => {
    const url = Linking.useURL()
    React.useEffect(() => {
        if (url) {
            const { queryParams } = Linking.parse(url)
            if (queryParams && queryParams['square_id']) {
                setStoreId(queryParams['square_id'] as string)
            }
        }
    }, [url])

    const [storeId, setStoreId] = useRecoilState(_storeId)
    const [syncCoupons, { loading, error, data }] = useMutation(SYNC_COUPONS, { variables: { store_id: storeId } })
    return <View style={{ flex: 1, margin: 16, gap: 16, alignItems: 'center' }}>
        {storeId ? <Button disabled={loading} label="Sync coupons" onPress={() => syncCoupons()} /> : <></>}
        {storeId ? <Button label="Sign out" onPress={() => setStoreId('')} /> : <Button label="Sign in"
            onPress={() => {
                signIn(url as string)
            }} />}
    </View>
}